spring:
  application:
    name: e-learning
  datasource:
    url: jdbc:mysql://localhost:3306/e_learning
    username: root
    password: manager
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  jackson:
    default-property-inclusion: non_null

server:
  port: 5000

api:
  base-path: /api/v1
  base-host: http://localhost:5000

logging:
  level:
    com.logicerror.e_learning: TRACE
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

app:
  course:
    default-thumbnail: storage/images/courses/default.png

