spring:
  application:
    name: e-learning
  datasource:
    url: jdbc:mysql://localhost:3306/e_learning
    username: root
    password: manager
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 5000

logging:
  level:
    org:
      springframework:
        security: TRACE
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}


api:
  base-path: /api/v1
